instance_size: 100
ori_nEdges: 990 # = the number of edges in graph * 2 (times 2 because of the graph representation in pytorch-geometric)
ori_node_dim: 1
ori_edge_dim: 4
sup_nNodes: 200
sup_nEdges: 3960 # = the number of edges * 4 * 2 (times 4 because of separation problem and times 2 because of the graph representation in pytorch-geometric)
sup_node_dim: 1
sup_edge_dim: 1
statistic_dim: 12
data_folder: ../data/maxcut_instances/100
user_callback: EnvCycleUserCallback
k: 10
limited_one_action: 2000
time_limit: 3000
reward_time_limit: -1000
terminal_gap: 0