instance_size: 100
ori_nEdges: 2000
ori_node_dim: 1
ori_edge_dim: 4
statistic_dim: 12
sup_nNodes: 100
sup_nEdges: 300
sup_node_dim: 1
sup_edge_dim: 1
data_folder: ../data/tsp_instances/100
user_callback: EnvUserCallback
k: 10
limited_one_action: 2000
time_limit: 3000
reward_time_limit: -1000
terminal_gap: 0.01
  