instance_size: 200
ori_nEdges: 4000
ori_node_dim: 1
ori_edge_dim: 4
statistic_dim: 12
sup_nNodes: 200
sup_nEdges: 600
sup_node_dim: 1
sup_edge_dim: 1
data_folder: ../data/tsp_instances/200
user_callback: EnvUserCallback
k: 10
limited_one_action: 2000
time_limit: 3000
reward_time_limit: -1000
terminal_gap: 0.01
reward_type: reward_shaping
state_extractor: PriorSubtourStateExtractor