feature_extractor:
  sup_feature_extractor: GNNGraphExtractor
  sup_hidden_size: 64
  sup_num_layers: 2
  sup_n_clusters: 2
  sup_dropout: 0
  ori_feature_extractor: GINEGraphExtractor
  ori_hidden_size: 64
  ori_num_layers: 2
  ori_n_clusters: 2
  ori_dropout: 0
  statistic_extractor: MLP
  statistic_hidden_sizes:
    - 128
  statistic_output_size: 64
dqn:
  verbose: 1
  batch_size: 1024
  target_update_interval: 1000
  train_freq: 
    - 16
    - step
  learning_starts: 4096
  gamma: 1
  buffer_size: 100000
  exploration_fraction: 0.5
  exploration_initial_eps: 1
  exploration_final_eps: 0.05
  gradient_steps: 2
  device: cuda:0
sac:
  verbose: 1
  batch_size: 256
  target_update_interval: 1000
  train_freq:
    - 16
    - step
  learning_starts: 4096
  gamma: 1
  buffer_size: 100000
  gradient_steps: 2
  device: cuda:0
learn:
  eval_freq: 2000
  n_eval_episodes: 1
  total_timesteps: 1000000
  log_interval: 1
  